# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI/home-fa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi
from PyQt5 import QtWidgets, QtCore
from PyQt5.QtWidgets import QApplication, QMainWindow, QDialog
import Resources
import os
import sys

# current_path = str(os.path.abspath(__file__)).strip("main.py")
current_path = "App/0.0.1"


# Main Window Class -> Home UI
class MainWindow(QMainWindow, QDialog):
    def __init__(self):
        super(MainWindow, self).__init__()
        # loadUi(f"{current_path}../UI/home-fa.ui", self)
        loadUi(f"{current_path}/UI/home-fa.ui", self)
        
        # Start Local DataBase Connection

        # define var

        # define Widgets

        # Pre Start

        # set Signals/Slots


# Books Screen Class -> Book UI
class Books_Screen(QDialog):
    def __init__(self, mainwindow):
        super().__init__()
        # set main
        self.mainwindow = mainwindow
        # load ui
        # loadUi(f"{current_path}../UI/book-fa.ui", self)
        loadUi(f"{current_path}/UI/book-fa.ui", self)

        # define var

        # define Widgets

        # Pre Start

        # set Signals/Slots


# Users Screen Class -> User UI
class Users_Screen(QDialog):
    def __init__(self, mainwindow):
        super().__init__()
        # set main
        self.mainwindow = mainwindow
        # load ui
        # loadUi(f"{current_path}../UI/user-fa.ui", self)
        loadUi(f"{current_path}/UI/user-fa.ui", self)

        # define var

        # define Widgets

        # Pre Start

        # set Signals/Slots


# Transactions Screen Class -> Transaction UI
class Transactions_Screen(QDialog):
    def __init__(self, mainwindow):
        super().__init__()
        # set main
        self.mainwindow = mainwindow
        # load ui
        # loadUi(f"{current_path}../UI/transaction-fa.ui", self)
        loadUi(f"{current_path}/UI/transaction-fa.ui", self)

        # define var

        # define Widgets

        # Pre Start

        # set Signals/Slots





def app_exit():
    print("Exiting")

if __name__ == "__main__":
    global mainwindow, todo, note
    app = QApplication(sys.argv)
    main_widgets = QtWidgets.QStackedWidget()
    
    mainwindow = MainWindow()
    book = Books_Screen(mainwindow)
    user = Users_Screen(mainwindow)
    transaction = Transactions_Screen(mainwindow)

    print(f"mainwindow= {main_widgets.addWidget(mainwindow)}")
    print(f"book= {main_widgets.addWidget(book)}")
    print(f"user= {main_widgets.addWidget(user)}")
    print(f"transaction= {main_widgets.addWidget(transaction)}")
    
    main_widgets.setFixedWidth(960)
    main_widgets.setFixedHeight(720)

    main_widgets.setWindowTitle("EasyLib - Library Management Application")
    main_widgets.show()

    try:
        sys.exit(app.exec_())
    except:
        app_exit()
